### ISSUE TITLE
user droidmaster does not exist

### ISSUE THREAD

**Issue by iamunixtz** [LinuxDroidMaster/Termux-Desktops#1]
When i run this script i get this errors
"Errors from xkbcomp are not fatal to the X server"
su: user droidmaster does not exist or the user entry does not contain all the required fields.

This means on that startxfce4_debian.sh script u hace to edit edit the sudo username from `droidmaster` to your sudo `username`

I Hope this will help
![Screenshot_20240112_001550_Termux](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/152855414/91d9d5ba-c733-4ad0-a962-460640ca4e93)

**Comment by LinuxDroidMaster** [comment]
I will create a note in the download section, thanks!

**Comment by Unvocal-linux** [comment]
Has this been resolved I tried to remove user sroidmaster but same error ? How to fix
