### ISSUE TITLE
Can't follow chroot guide

### ISSUE THREAD

**Issue by astroskyoffical** [LinuxDroidMaster/Termux-Desktops#10]
Unfortunately even after being rooted.  Magisk busybody module flashed and followed your guide to the T.   Running that start.sh script says it can't find busy box

Pin: release a=*
Pin-Priority: -10
droidmaster@localhost:~$ exit
logout
root@localhost:~# exit
logout
:/data/local/tmp # exit
~ $ sudo nano /data/local/tmp/start.sh
~ $ sudo XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac &
sudo busybox mount --bind $PREFIX/tmp /data/local/tmp/chrootubuntu/tmp

sh /data/local/tmp/start.sh
[2] 14455

[2]+  Stopped                 sudo XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac
/data/local/tmp/start.sh: 7: busybox: not found
/data/local/tmp/start.sh: 9: busybox: not found
/data/local/tmp/start.sh: 10: busybox: not found
/data/local/tmp/start.sh: 11: busybox: not found
/data/local/tmp/start.sh: 12: busybox: not found
/data/local/tmp/start.sh: 15: busybox: not found
/data/local/tmp/start.sh: 18: busybox: not found
/data/local/tmp/start.sh: 21: busybox: not found
~ $ exit
logout
There are stopped jobs.
~ $

This is weird considering busybox is indeed installed. I tried rebooting. Restarting from scratch. Reflashing.   Just can't proceed past these final steps. 

I'm running android 13.   Full root.   OnePlus 8t.   There shouldn't be much difference than most other rooted setups.

**Comment by LinuxDroidMaster** [comment]
Hi I think this command is wrong: `sudo XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac &` you shouldn't use `sudo` in that part just: 

```
XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac &
sudo busybox mount --bind $PREFIX/tmp /data/local/tmp/chrootubuntu/tmp

sh /data/local/tmp/start.sh
```

Also could you show the content of your start.sh file? I got that message when trying to setup everything and it was related to using sudo and being inside or outside the root shell (it is a bit messy)

**Comment by astroskyoffical** [comment]
Yeah so I followed the guide to the T but this is the contents of my sh script. 
![PSX_20240409_144148](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/101475363/da6af658-8ccd-4d93-a5cd-a40736e635b6)


Also I get this error every time I run what you just said to run. 
![PSX_20240409_144242](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/101475363/24e4e631-e278-48e5-8c80-7e8b1e15c591). 
![PSX_20240409_144311](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/101475363/5b740727-d846-4105-998e-2c7b10dfd5f1)

**Comment by astroskyoffical** [comment]
Bump just wondering if you saw this. 

Here's the output when I run what you said btw 
![PSX_20240410_134810](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/101475363/4edbde88-604b-4bb1-a452-0ae00babefb2)

**Comment by LinuxDroidMaster** [comment]
Sorry for the late response! I'm not sure why busybox is still not recognized after installing it. Could you try installing other version of busybox? from the same page.

**Comment by ask9027** [comment]
use linuxdeploy
