### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by SalehObb** [LinuxDroidMaster/Termux-Desktops#11]
Every time i login debian i access droidmaster user
But i dont want that
SomeOne explain 
How can i change  droidmaster user
To my user

**Comment by LinuxDroidMaster** [comment]
Just modify where it says "droidmaster" in the startxfce4... script. You can do it with nano and just replace in the last line `droidmaster` with your username

**Comment by SalehObb** [comment]
What is the path after i inter nano ?

**Comment by LinuxDroidMaster** [comment]
Navigate to the path you downloaded the script (check it with `ls` command) and then modify it with `nano startxfce4.......`

**Comment by SalehObb** [comment]
Thanks
