### ISSUE TITLE
Issue launching environment following install script execution

### ISSUE THREAD

**Issue by Cap980** [LinuxDroidMaster/Termux-Desktops#14]
Hello, I was giving your Debian automated install script a run. Device is obviously rooted, BusyBox good to go, all packages you listed installed before hand. 

The install script went smoothly, not issues I noticed. When executing the startxfce4_chrootDebian.sh  there is a bind failure with dbus, permission issue.

~ $ sh startxfce4_chrootDebian.sh
termux-x11: no process found
Xwayland: no process found
pulseaudio: no process found
virgl_test_server_android: no process found
termux-wake-lock: no process found
Starting: Intent { cmp=com.termux.x11/.MainActivity }
Warning: Activity not started, intent has been delivered to currently running top-most instance.
mkdir: '/data/local/tmp/chrootDebian/dev/shm': File exists
mkdir: '/data/local/tmp/chrootDebian/sdcard': File exists
dbus-daemon[25905]: Failed to start message bus: Failed to bind socket "/tmp/dbus-MDZWKL9ArX": Permission denied
EOF in dbus-launch reading address from bus daemon

Figured I would ask if this is something you have run into, or if that script is still a work in progress before I go looking into it myself.

**Comment by LinuxDroidMaster** [comment]
Hi! The script works fine for my devices but is still a work in progress so all the errors you find are welcome to improve it. Can you execute the script `start_debian.sh`? You need go root and it should be in the `/data/local/tmp/` folder

````
su
cd /data/local/tmp
sh start_debian.sh
```

After executing it you should be into the debian chroot environment but lets see if it throws some error

**Comment by Cap980** [comment]
I believe I located the issue relating to my initial post and fixed it, the only remaining thing is getting the GUI to show up X11. I see the X11 session start and the app go black as if its loading in, but it never gets to the desktop, I think it may be related to the display export options, I am going to mess with it more.

**Comment by Cap980** [comment]
Okay I got it working normally. I am curious though, do you have any method as of yet to have the entire desktop environment accelerated by default? Until rooting and setting this up, I use a proot and anything launched inside the DE was accelerated automatically. I imagine the usage of the driver will be different than with setting it in a proot.

**Comment by LinuxDroidMaster** [comment]
You can use the same proot commands and hardware acceleration config in chroot. Could you give me more details on how you solved the errors? In case other user have the same problems

**Comment by Cap980** [comment]
My particular issue ended up being that my user account in the chroot was not made while the initial script ran, then I had forgotten to add it to the sudoers file after I created it manually. So I was getting various permission issues, partially my fault.

Not sure why the script didn't create it, it prompted for a username and password as expected. I unfortunately didn't save the output of the script to go back and look.

**Comment by hzykiss** [comment]
> 我相信我找到了与我最初帖子有关的问题，并修复了它，唯一剩下的事情就是让GUI显示X11。我看到X11会话启动，应用程序变黑，好像它加载进来一样，但它永远不会到达桌面，我想这可能与显示导出选项有关，我将更混乱它。

Hello, how did you fix it? I encountered the same problem.
