### ISSUE TITLE
Can't chroot into debian

### ISSUE THREAD

**Issue by Androser420** [LinuxDroidMaster/Termux-Desktops#17]
i tried setting up the debian chroot manually since automatic one didnt work
turns out i cant chroot into it because i get this error:

su: cannot open session: Error in service module

any ideas on how to fix this?

**Comment by LinuxDroidMaster** [comment]
Hi! Can you tell me which device do you have? I think there is a problem with samsung devices but it should be possible to fix it

**Comment by Androser420** [comment]
yeah it indeed is a samsung - galaxy s10 lite

**Comment by LinuxDroidMaster** [comment]
Can you verify if you have dbus-x11 package installed? If not pls install it (`sudo apt install dbus-x11`) and try running the script again

**Comment by LinuxDroidMaster** [comment]
Hey this seems to be the fix for the Samsung devices: https://www.reddit.com/r/termux/comments/1biq4pw/comment/kw0zdbf/

```
chmod -R 1777 /tmp
chown -R root:root /tmp
```

**Comment by Androser420** [comment]
i was able to chroot into debian but now not even basic commands work like chmod or ls
