### ISSUE TITLE
Cannot find mesa-zink & virglrenderer-mesa-zink in termux repositories

### ISSUE THREAD

**Issue by Wallclip** [LinuxDroidMaster/Termux-Desktops#19]
I tried to follow the hardware acceleration guide, but couldn't continue due to pkg being unable to locate mesa-zink & virglrenderer-mesa-zink, even after pkg update and pkg upgrade, i also tried changing repositories.

**Comment by lesca** [comment]
+1 
```
Unable to locate package mesa-zink
Unable to locate package virglrenderer-mesa-zink
```
checked the packages source, not found such packages
https://github.com/termux/termux-packages

**Comment by LinuxDroidMaster** [comment]
I think you need to install first one of these: 

```
pkg update
pkg upgrade
pkg install x11-repo
pkg install termux-x11-nightly
pkg install tur-repo
```
![image_2024-05-07_075756555](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/155466495/37fb3939-92c8-4f98-abef-b698c4d73064)

**Comment by Wallclip** [comment]
> I think you need to install first this:
> 
> ```
> pkg update
> pkg upgrade
> pkg install tur-repo
> ```
> 
> ![image_2024-05-07_075756555](https://private-user-images.githubusercontent.com/155466495/328404335-37fb3939-92c8-4f98-abef-b698c4d73064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzU3NjEsIm5iZiI6MTcxNTA3NTQ2MSwicGF0aCI6Ii8xNTU0NjY0OTUvMzI4NDA0MzM1LTM3ZmIzOTM5LTkyYzgtNGY5OC1hYmVmLWI2OThjNGQ3MzA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwOTUxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmE3MDE4N2I3OGZkMTBmZTE4MzZkMTI5MGE2YmMzNTliZTk0M2FjOTY3ZGVjNWEzYjU4NWQ5NjdkZmEyOTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C_OlwM0c-tumF2UGK7Lon-r1K3AvNxzANuRxQbGdesA)

Thanks.
