### ISSUE TITLE
Error: proot-distro should not be executed under PRoot.

### ISSUE THREAD

**Issue by iamunixtz** [LinuxDroidMaster/Termux-Desktops#2]
I gwt this error 
Error: proot-distro should not be executed under PRoot.

When i run the script startxfce4_debian.sh on proot debian i get that error please solve this 
![Screenshot_20240112_001924_Termux](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/152855414/a068b88a-93a4-4a5b-9b75-f36701344677)

**Comment by LinuxDroidMaster** [comment]
You need to run the script in Termux out of proot-distro. Tell me if now it works

**Comment by LinuxDroidMaster** [comment]
So after running the script you open Termux X11 and the Linux Desktop appears but the cursor doesn't move? The warnings and all that messages are not something you should worry about. The only thing from your screenshot is that you have already an X server opened, close it (close both apps, Termux X11 and Termux and check you don't have the notifications in your device to be sure they are fully closed)  and then open again termux and execute the script again. 

btw, I'm pending improving the scripts checking and closing other X servers and launching Termux X11 automatically but you should be able to use it right now without too much problems. I recommend you checking the video where I show all the process too

**Comment by LinuxDroidMaster** [comment]
@iamunixtz let me know if its fixed to close the issue

**Comment by robr18** [comment]
How do you run the script out of proot-distro?

**Comment by iamunixtz** [comment]
> How do you run the script out of proot-distro?

Run from the new terminal not inside the proot

**Comment by Joebim** [comment]
I got this error after running it outside proot

su: user droidmaster does not exist or the user entry does not contain all the required fields

what do i do
