### ISSUE TITLE
dbus-launching issue

### ISSUE THREAD

**Issue by Tasin269** [LinuxDroidMaster/Termux-Desktops#21]
Whenever I start debian I got this output and x11 shows blank screen
termux-x11: no process found
Xwayland: no process found
Starting: Intent { cmp=com.termux.x11/.MainActivity }
-bash: line 1: dbus-launch: command not found

**Comment by LinuxDroidMaster** [comment]
Hi can you check if you have installed dbus-x11?

**Comment by Tasin269** [comment]
Thanks I installed the dbus-x11 and now it's working
