### ISSUE TITLE
Session Closed When Start the Terminal on debian 

### ISSUE THREAD

**Issue by iamunixtz** [LinuxDroidMaster/Termux-Desktops#3]
Session start the well with some errors but when open Termux x11 it will open but when try to start the terminal it will closed the session automatically. And termux X11 it will say **not conected** the session will die on termux to idont know uf this will be due to my phone or it just script bug 
![Screenshot_20240112_143246_Termux](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/152855414/be62038e-0b6f-4658-9742-32b4f41ddd10)

**Comment by LinuxDroidMaster** [comment]
Thats because you have Android 12 or greater. You need to disable phantom processes so the system doesn't stop Termux. I'm publishing a video about that on Monday, but you can fix that with this: https://ivonblog.com/en-us/posts/fix-termux-signal9-error/

**Comment by iamunixtz** [comment]
Okay thanks for Your help 🫡
