### ISSUE TITLE
Zink on chroot ?

### ISSUE THREAD

**Issue by 3bdelrhman-rabie** [LinuxDroidMaster/Termux-Desktops#6]
Hello 

When I tried zink method and virgl method on a chrooted system ,on a14 and sd 732g with adreno 618 

![Screenshot_20240211-150413_Termux_X11](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/95903278/0f4835c8-4f81-487b-8495-0d145060e1d3)
![Screenshot_20240211-151016_Termux_X11](https://github.com/LinuxDroidMaster/Termux-Desktops/assets/95903278/667277fe-3923-4d57-96f0-577c587b28ae)

Got these errors 

Note : 
I mounted tmp of termux on chroot tmp 

I have latest termux x11 version ,dont know if that XDG issue is because ot or not 

Thanks

**Comment by LinuxDroidMaster** [comment]
Hi! I didn't see that issue sorry. I don't have chroot so I can't answer properly but if you take a look at the start... scripts you should be exporting the XDG variable already, could you check that?
