### ISSUE TITLE
Gran trabajo

### ISSUE THREAD

**Issue by LeonardoE549** [LinuxDroidMaster/Termux-Desktops#7]
Hola, este proyecto está increíble muchas gracias por crearlo y por qué te tomaste el tiempo para hacer esto increíble. Admiro y te felicito por tu gran trabajo. Espero que tengas un buen día😃.

**Comment by LinuxDroidMaster** [comment]
Muchas gracias por tu comentario! Espero que te resulte de ayuda y si consideras que se puede mejorar algo estoy abierto a sugerencias 😄
