### ISSUE TITLE
Agregar Alpine, Void y Archlinux

### ISSUE THREAD

**Issue by LeonardoE549** [LinuxDroidMaster/Termux-Desktops#8]
Seria buenísimo si pudieras hacer un tutorial de como instalar algunas distribuciones como Alpine, Void o Arch Linux, seria muy interesante. Yo personalmente instalé Ubuntu 23.10 usando tus tutorial y modificando los Scripts que hiciste, pero desconozco cómo hacerlos con las distros que ya nombre por qué son comandos diferentes a los de debian y derivados. Que tenga un buen día 😃.

**Comment by LinuxDroidMaster** [comment]
Buenas! Pues planeo hacerlos en cuanto tenga tiempo. Yo también estoy acostumbrado más a los comandos de Debian y Ubuntu pero quiero echarle un vistazo a Arch y Alpine y hacer vídeos al respecto
